public class test16 {
    public string name{get;set;}
    public string industry{get;set;}
    public integer rating{get;set;}
    public string ownership{get;set;}

    public void setdata(){
        name='Mayur';
        industry='Softwere';
        rating=5;
        ownership='MG group';
    }
    public void invoke(){
        name='Wipro';
        industry='Softwere';
        rating=51;
        ownership='private';
        
    }
}